### ISSUE TITLE
Cooking for Blockheads Cooking Table Crash

### ISSUE THREAD

**Issue by sforzando02** [jadedcat/MF3Configs#28]
http://pastebin.com/HPGBUMKs < here is the log file in the game output. It doesn't actually provide a crash log but recently, whenever I try to access the cooking table (I keep trying to type oven so pastebin says oven but it really is the table) from cooking for blockheads it shuts down my single-player like a multi-player world. I will right click with both an empty hand or with an item in my hand and the screen pops up that says "A fatal error has occured, this connection is terminated" and will then send me to the multiplayer screen looking for a valid server to connect to.

Not sure why it is doing it because as of yesterday, it worked fine. 

I am in version 1.1.35 from the Curse Client.

Thanks for the help!

EDIT: Okay so I did some digging and took all the stuff out of the fridges and found that vanilla wheat seeds are causing the crash. Not sure about the others though.

**Comment by agentGH72** [comment]
Ok... this is not a fix but I seemed to have found a work around. What I did was craft another Cooking for Blockheads 1 book and then open and close the book. Then I used the cooking table. This seems to keep cooking table from crashing to the multiplayer screen.

**Comment by Moojuiceman** [comment]
**Seed soup**, that's the issue. A combination of any seed and Harvestcraft stock is what does it for me. Just having them in my inventory (not in the fridge) causes the issue when opening the table. Seems to happen with any seed that's usable in seed soup.

EDIT: Also happens when opening 'Cooking for blockheads I' as if the GUI can't handle displaying seed soup

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#11
